import 'package:flutter/material.dart';
import 'package:babyshophub/core/constants/light_color_scheme.dart';

TextTheme lightTextTheme = TextTheme(
  displayLarge: TextStyle(
      fontSize: 96.0,
      fontWeight: FontWeight.w300,
      color: lightColorScheme.onSurface,
      letterSpacing: -1.5),
  displayMedium: TextStyle(
      fontSize: 60.0,
      fontWeight: FontWeight.w300,
      color: lightColorScheme.onSurface,
      letterSpacing: -0.5),
  displaySmall: TextStyle(
      fontSize: 48.0,
      fontWeight: FontWeight.w400,
      color: lightColorScheme.onSurface),
  headlineMedium: TextStyle(
      fontSize: 34.0,
      fontWeight: FontWeight.w400,
      color: lightColorScheme.onSurface,
      letterSpacing: 0.25),
  headlineSmall: TextStyle(
      fontSize: 24.0,
      fontWeight: FontWeight.w400,
      color: lightColorScheme.onSurface),
  titleLarge: TextStyle(
      fontSize: 20.0,
      fontWeight: FontWeight.w900,
      color: lightColorScheme.onSurface,
      letterSpacing: 0.15),
  titleMedium: TextStyle(
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      color: lightColorScheme.onSurface,
      letterSpacing: 0.15),
  titleSmall: TextStyle(
      fontSize: 14.0,
      fontWeight: FontWeight.w500,
      color: lightColorScheme.onSurface,
      letterSpacing: 0.1),
  bodyLarge: TextStyle(
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      color: lightColorScheme.onSurface,
      letterSpacing: 0.5),
  bodyMedium: TextStyle(
      fontSize: 14.0,
      fontWeight: FontWeight.w400,
      color: lightColorScheme.onSurface,
      letterSpacing: 0.25),
  bodySmall: TextStyle(
      fontSize: 12.0,
      fontWeight: FontWeight.w400,
      color: lightColorScheme.onSurface,
      letterSpacing: 0.4),
  labelLarge: TextStyle(
      fontSize: 14.0,
      fontWeight: FontWeight.w500,
      color: lightColorScheme.onSurface,
      letterSpacing: 1.25),
  labelSmall: TextStyle(
      fontSize: 10.0,
      fontWeight: FontWeight.w400,
      color: lightColorScheme.onSurface,
      letterSpacing: 1.5),
);
